# Generated by Django 2.0.6 on 2018-07-05 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='教程标题')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
            ],
            options={
                'verbose_name': '教程',
                'verbose_name_plural': '教程',
            },
        ),
        migrations.CreateModel(
            name='CourseVideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(max_length=50, verbose_name='目录标题')),
                ('index', models.IntegerField(default=999, verbose_name='目录的排序')),
                ('videoUrl', models.TextField(verbose_name='视频url')),
            ],
            options={
                'verbose_name': '教程目录',
                'verbose_name_plural': '教程目录',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='coursevideolist',
            name='courseVideo_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.Course', verbose_name='教程标题'),
        ),
    ]
