# Generated by Django 2.0.6 on 2018-07-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180705_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursevideo',
            options={'verbose_name': '教程视频', 'verbose_name_plural': '教程视频'},
        ),
        migrations.AlterModelOptions(
            name='coursevideolist',
            options={'verbose_name': '教程视频目录内容', 'verbose_name_plural': '教程视频目录内容'},
        ),
        migrations.AlterField(
            model_name='coursevideolist',
            name='courseVideo_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.CourseVideo', verbose_name='教程视频'),
        ),
    ]
