# Generated by Django 2.0.6 on 2018-08-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180705_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselist',
            options={'ordering': ['index'], 'verbose_name': '教程目录', 'verbose_name_plural': '教程目录'},
        ),
        migrations.AlterModelOptions(
            name='coursevideolist',
            options={'ordering': ['index'], 'verbose_name': '教程视频目录内容', 'verbose_name_plural': '教程视频目录内容'},
        ),
        migrations.AlterField(
            model_name='coursevideolist',
            name='videoUrl',
            field=models.CharField(max_length=100, verbose_name='视频url'),
        ),
    ]
