# Generated by Django 2.0.6 on 2018-09-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20180813_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='proUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='用户名称')),
                ('pasw', models.CharField(max_length=30, verbose_name='密码')),
            ],
            options={
                'verbose_name': '普通用户',
                'verbose_name_plural': '普通用户',
            },
        ),
    ]
