# Generated by Django 2.0.6 on 2019-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_prouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAppWeixininfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('from_name', models.CharField(max_length=50)),
                ('read_num', models.CharField(blank=True, max_length=20, null=True)),
                ('like_num', models.CharField(blank=True, max_length=20, null=True)),
                ('articleurl', models.CharField(blank=True, db_column='articleUrl', max_length=350, null=True)),
                ('shijianchuo', models.CharField(max_length=50)),
                ('digest', models.CharField(blank=True, max_length=300, null=True)),
                ('updete_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'first_app_weixininfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jingdong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(blank=True, db_column='productId', max_length=100, null=True)),
                ('productname', models.CharField(blank=True, db_column='productName', max_length=100, null=True)),
                ('shopname', models.CharField(blank=True, db_column='shopName', max_length=100, null=True)),
                ('commentnums', models.CharField(blank=True, db_column='commentNums', max_length=100, null=True)),
                ('prices', models.CharField(blank=True, max_length=20, null=True)),
                ('links', models.CharField(blank=True, max_length=255, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '京东信息',
                'verbose_name_plural': '京东信息',
                'ordering': ['productname'],
            },
        ),
    ]
