# Generated by Django 2.0.6 on 2019-04-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_firstappweixininfo_jingdong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ouwang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='title', max_length=100, null=True)),
                ('ctt', models.TextField(db_column='comtent', verbose_name='文章内容')),
                ('date', models.CharField(blank=True, db_column='date', max_length=100, null=True)),
                ('visitCount', models.CharField(blank=True, db_column='visitCount', max_length=100, null=True)),
                ('LinkUrl', models.CharField(blank=True, db_column='LinkUrl', max_length=100, null=True)),
            ],
            options={
                'verbose_name': '瓯网信息',
                'verbose_name_plural': '瓯网信息',
                'ordering': ['title'],
            },
        ),
    ]
