# Generated by Django 2.0.6 on 2019-04-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_ouwang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouwang',
            name='visitCount',
            field=models.IntegerField(db_column='visitCount', default=999, verbose_name='点击数'),
        ),
    ]
