# Generated by Django 2.0.6 on 2019-04-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20190420_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouwang',
            name='visitCount',
            field=models.CharField(blank=True, db_column='visitCount', max_length=100, null=True),
        ),
    ]
