# Generated by Django 2.0.6 on 2019-05-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_doupantop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doupantop',
            options={'ordering': ['movie_name'], 'verbose_name': '豆瓣', 'verbose_name_plural': '豆瓣'},
        ),
        migrations.RemoveField(
            model_name='doupantop',
            name='movieInfo',
        ),
        migrations.RemoveField(
            model_name='doupantop',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='doupantop',
            name='star',
        ),
        migrations.RemoveField(
            model_name='doupantop',
            name='title',
        ),
        migrations.AddField(
            model_name='doupantop',
            name='actor',
            field=models.CharField(blank=True, db_column='actor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='another_name',
            field=models.CharField(blank=True, db_column='another_name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='comment_times',
            field=models.CharField(blank=True, db_column='comment_times', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='date',
            field=models.CharField(blank=True, db_column='date', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='director',
            field=models.CharField(blank=True, db_column='director', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='grade',
            field=models.CharField(blank=True, db_column='grade', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='introduction',
            field=models.CharField(blank=True, db_column='introduction', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='language',
            field=models.CharField(blank=True, db_column='language', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='length',
            field=models.CharField(blank=True, db_column='length', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='movie_name',
            field=models.CharField(blank=True, db_column='movie_name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='no',
            field=models.CharField(blank=True, db_column='no', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='region',
            field=models.CharField(blank=True, db_column='region', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='typee',
            field=models.CharField(blank=True, db_column='typee', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doupantop',
            name='writer',
            field=models.CharField(blank=True, db_column='writer', max_length=100, null=True),
        ),
    ]
