# Generated by Django 2.0.6 on 2019-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_auto_20190515_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doupantop',
            name='director',
            field=models.CharField(blank=True, db_column='director', max_length=1000, null=True),
        ),
    ]
