# Generated by Django 2.0.6 on 2019-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_auto_20190515_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doupantop',
            name='actor',
            field=models.CharField(blank=True, db_column='actor', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doupantop',
            name='region',
            field=models.CharField(blank=True, db_column='region', max_length=1000, null=True),
        ),
    ]
